GXSetNumChans(1);

GXSetChanCtrl(
	GX_COLOR0A0,
	GX_DISABLE,  
	GX_SRC_REG,   
	GX_SRC_REG,   
	GX_LIGHT_NULL,
	GX_DF_NONE,   
	GX_AF_NONE);

GXSetNumTexGens(1);
GXSetTexCoordGen(GX_TEXCOORD0, GX_TG_MTX2x4, GX_TG_TEX0, GX_IDENTITY);