GXSetNumChans(1);

GXSetChanCtrl(
	GX_COLOR0,
	GX_FALSE,
	GX_SRC_REG,
	GX_SRC_REG,
	0,
	GX_DF_CLAMP,
	GX_AF_SPOT);

GXSetChanCtrl(
	GX_ALPHA0,
	GX_FALSE,
	GX_SRC_REG,
	GX_SRC_REG,
	0,
	GX_DF_CLAMP,
	GX_AF_SPOT);

GXSetNumTexGens(4);

GXSetTexCoordGen(GX_TEXCOORD0, GX_TG_MTX3x4, GX_TG_POS, GX_TEXMTX0);
GXSetTexCoordGen(GX_TEXCOORD1, GX_TG_MTX2x4, GX_TG_TEX0, GX_TEXMTX1);
GXSetTexCoordGen(GX_TEXCOORD2, GX_TG_MTX2x4, GX_TG_TEX0, GX_TEXMTX2);
GXSetTexCoordGen(GX_TEXCOORD3, GX_TG_MTX2x4, GX_TG_TEX1, GX_IDENTITY);